---
- name: Deploy web app
  hosts: node2
  become: true

  tasks: 
  - name: Install git
    yum: 
      name: git
      state: present

  - name: Clone code
    git: 
      repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
      dest: var/www/html
      force: yes


  
...