---
- name: Install Apache server
  become: yes
  hosts: Group1
  

  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "ubuntu"

  - name: start up apache service
    service: 
      name: apache2
      state: started
    when: ansible_distribrution == "Ubuntu"


  - name: Enable apache2
    service: 
      name: apache2
      enabled: yes
    when: ansible_distribrution == "Ubuntu"

  - name: Install httpd
    yum:
      name: Httpd
      state: present
    when: ansible_distribrution == "Amazon"

  - name: start up Httpd server
    service: 
      name: Httpd
      state: started
    when: ansible_distribrution == "Amazon"

  - name: Enable Httpd
    service: 
      name: Httpd
      enabled: yes
    when: ansible_distribrution == "Amazon"