---
- name: using variables
  hosts: node1
  become: yes
  vars:
    username: Bervelyn123

  tasks:
  - name: update dynamic page
    template: 
      src: dynamic.j2
      dest: /var/www/html/dynamic.html
...